// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: "us-west-2",
    aws_cognito_identity_pool_id: "us-west-2:0c3677b5-04ca-44a4-b200-7c3bb27a7a68",
    aws_cognito_region: "us-west-2",
    aws_user_pools_id: "us-west-2_nu1CRoQ6X",
    aws_user_pools_web_client_id: "7jb5b7kuovnrvssbs25p79pbeh",
    oauth: {
        domain: "studygroupsmobile6a1820d9-6a1820d9-local.auth.us-west-2.amazoncognito.com",
        scope: ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"],
        redirectSignIn: "exp://127.0.0.1:19000/--/",
        redirectSignOut: "exp://127.0.0.1:19000/--/",
        responseType: "token"
    },
    federationTarget: "COGNITO_USER_POOLS"
};

export default awsmobile;
